husky/feedback/urls.py
#Amin Husni - 2018
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'feedback'
urlpatterns = [
    path('', views.index, name='index'),
    path('setup.html', views.setup, name='setup'),
    path('setlocation.html', views.setlocation, name='setlocation'),
    path('rating_submit.html', views.rating_submit, name='rating_submit'),
    path('problem.html', views.problem, name='problem'),
    path('problem_submit.html', views.problem_submit, name='problem_submit'),
    path('thankyou.html', views.thankyou, name='thankyou'),

    
]

husky/husky/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponseRedirect

urlpatterns = [
    path('feedback/', include('feedback.urls')),
    path('supervisor/', include('supervisor.urls')),
    path('admin/', admin.site.urls),
]

husky/supervisor/urls.py
#Amin Husni - 2018
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'supervisor'
urlpatterns = [
    path('', views.index, name='index'),
    path('authenticate.html', views.authenticate, name='authenticate'),
    path('checklist.html', views.checklist, name='checklist'),
    path('error.html', views.error, name='error'),
    path('checklist_submit.html', views.checklist_submit, name='checklist_submit'),
    path('supervisor_index.html', views.supervisor_index, name='supervisor_index'),
    path('checklist_report.html', views.checklist_report, name='checklist_report'),
    path('checklist_report_location.html', views.checklist_report_location, name='checklist_report_location'),
    path('performance_report_location.html', views.performance_report_location, name='performance_report_location'),
    path('performance_report.html', views.performance_report, name='performance_report'),
    path('report_csv.html', views.report_csv, name='report_csv'),
]

husky/feedback/models.py
#Amin Husni - 2018
from django.db import models

# Create your models here.
class Feedback(models.Model):

    # Fields
    rating = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True, editable=False)
    location_id = models.TextField(max_length=100)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return str(self.created)


class Problem(models.Model):

    # Fields
    feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE)
    clogged = models.BooleanField(default=False)
    toilet_paper = models.BooleanField(default=False)
    lighting = models.BooleanField(default=False)
    soap = models.BooleanField(default=False)
    hose = models.BooleanField(default=False)
    temperature = models.BooleanField(default=False)
    bowl = models.BooleanField(default=False)
    sink = models.BooleanField(default=False)
    smell = models.BooleanField(default=False)
    fault = models.BooleanField(default=False)


    def __str__(self):
        return str(self.feedback)

husky/feedback/views.py
#Amin Husni - 2018
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from feedback.models import Feedback, Problem
from location.models import Location
from django.shortcuts import redirect
import logging
from telegram.ext import Updater, CommandHandler, MessageHandler
import telegram.ext
import threading



# Create your views here.
bot = telegram.Bot(token='574491770:AAEEuzsNjFvVUj8q6Abxd1YUdI7pduSHobA')
chat_id = -304829808
#Telegram

def index(request):
    
    if not request.COOKIES.get('location_id'):
        return redirect('feedback:setup')

    else:
        return render(request, 'feedback/index.html', None)

def setup(request):
    locations = Location.objects.all()
    context = {
        'locations': locations,
    }
    return render(request, 'feedback/setup.html', context)
    
def setlocation(request):

    response = redirect('feedback:index')
    response.set_cookie('location_id', request.POST['location_id'])
    return response

def rating_submit(request):

    rating = int(request.POST['rating'])
    location_id = request.COOKIES.get('location_id')
    currentfeedback = Feedback(rating=rating, location_id=location_id)
    currentfeedback.save()

    if rating < 3:
        return render(request, 'feedback/problem.html', {'feedback_id': currentfeedback.id})
    else:
        return redirect('feedback:thankyou')

def thankyou(request):
    return render(request, 'feedback/thankyou.html', None)

def alert_telegram(location_name, location_id):
    try:
        alerttext = "Problem at "+location_name + "(ID: "+location_id+")"
        bot.sendMessage(chat_id=chat_id, text=alerttext)
    except:
        pass
    
def problem_submit(request):

    feedback_id = request.POST['feedback_id']

    if 'clogged' not in request.POST:
        clogged = False
    else:
        clogged = bool(request.POST['clogged'])   

    if 'toilet_paper' not in request.POST:
        toilet_paper = False
    else:
        toilet_paper = bool(request.POST['toilet_paper'])

    if 'lighting' not in request.POST:
        lighting = False
    else:
        lighting = bool(request.POST['lighting'])

    if 'soap' not in request.POST:
        soap = False
    else:
        soap = bool(request.POST['soap'])

    if 'hose' not in request.POST:
        hose = False
    else:
        hose = bool(request.POST['hose'])

    if 'temperature' not in request.POST:
        temperature = False
    else:
        temperature = bool(request.POST['temperature'])

    if 'bowl' not in request.POST:
        bowl = False
    else:
        bowl = bool(request.POST['bowl'])

    if 'sink' not in request.POST:
        sink = False
    else:
        sink = bool(request.POST['sink'])

    if 'smell' not in request.POST:
        smell = False
    else:
        smell = bool(request.POST['smell'])

    if 'fault' not in request.POST:
        fault = False
    else:
        fault = bool(request.POST['fault'])

    feedbackprev = Feedback.objects.get(pk=feedback_id)
    problems = Problem(feedback=feedbackprev, clogged=clogged, toilet_paper=toilet_paper, lighting=lighting, soap=soap, hose=hose, temperature=temperature, bowl=bowl, sink=sink, smell=smell, fault=fault)
    problems.save()
    location_id = feedbackprev.location_id
    location = Location.objects.get(location_id=location_id)
    location_name = location.location_name

    #Telegram Alert Part
    bot_thread = threading.Thread(target=alert_telegram, args=[location_name, location_id])
    bot_thread.setDaemon(False)
    bot_thread.start()


    return redirect('feedback:thankyou')


def problem(request):
    return render(request, 'feedback/problem.html', None)

husky/feedback/templates/feedback/index.html
{% load staticfiles %}

<!-- Amin Husni - 2018 -->
<head>
		<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
				<title>Husky</title>
				<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
					<link rel="stylesheet" href="{% static 'css/old.css' %}">
					</head>
<body style="background:url( {% static 'img/bg.jpg' %} );background-size:120%;font-family:Verdana;">
    <table style="width:100%;text-align:center;font-weight:bold;color:#fff;table-layout: fixed">

        <tr class="first">
            <td colspan="5"><h1 style="font-size:60px;margin-top:100px;padding-bottom:50px;">Good Day<br />Please rate our toilet</h1></td>
		</tr>
		<form action="{% url 'feedback:rating_submit' %}", method="post">
				{% csrf_token %}
        <tr class="first" style="font-size:30px;">
				<td><button name="rating" value="5" type="submit" style="background:transparent;border: 0px solid #4992B7"><img class="vote" rel="5" src="{% static 'img/excellent.png' %}" /><br /><font color="white">Excellent</font></button></td>
				<td><button name="rating" value="4" type="submit" style="background:transparent;border: 0px solid #4992B7"><img class="vote" rel="4" src="{% static 'img/good.png' %}" /><br /><font color="white">Good</font></button></td>
				<td><button name="rating" value="3" type="submit" style="background:transparent;border: 0px solid #4992B7"><img class="vote" rel="3" src="{% static 'img/average.png' %}" /><br /><font color="white">Average</font></button></td>
				<td><button name="rating" value="2" type="submit" style="background:transparent;border: 0px solid #4992B7"><img class="vote" rel="2" src="{% static 'img/poor.png' %}" /><br /><font color="white">Poor</font></button></td>
				<td><button name="rating" value="1" type="submit" style="background:transparent;border: 0px solid #4992B7"><img class="vote" rel="1" src="{% static 'img/sad.png' %}" /><br /><font color="white">Sad</font></button></td>
		</tr>
	</form>
        <tr class="first">
            <td colspan="5"><br /><br /><br /><br /><br /><br /><span style="display:block;font-size:20px;">This screen is sanitised regularly</span></td>
        </tr>
</table>
</body>

<!-- <!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
				<title>Husky</title>
				<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
					<link rel="stylesheet" href="{% static 'css/old.css' %}">
					</head>
					<body style="overflow:hidden;">
						<div class="row">
							<div class="col">
								<h1 class="text-center" style="height:256px;font-size:100px;padding:182px;">Please Give Us Your Feedback</h1>
							</div>
						</div>
						<div class="row justify-content-center" style="margin-top:100px;">

                        <form action="{% url 'feedback:rating_submit' %}", method="post">
                                {% csrf_token %}
							<button name="rating" value="5" class="btn btn-primary btn-lg" type="submit" style="margin-right:0px;height:250px;width:250px;box-shadow:none;background-color:rgb(43,201,79);border-color:white;">😄</button>
							<button name="rating" value="4" class="btn btn-primary btn-lg" type="submit" style="margin-right:0px;height:250px;width:250px;box-shadow:none;background-color:rgb(24,163,2);border-color:white;">😊</button>
							<button
            name="rating" value="3" class="btn btn-primary btn-lg" type="submit" style="margin-right:0px;height:250px;width:250px;box-shadow:none;border-color:white;">😑</button>
							<button name="rating" value="2" class="btn btn-primary btn-lg" type="submit" style="margin-right:0px;height:250px;width:250px;outline:none;background-color:rgb(239,244,26);box-shadow:none;border-color:white;color:rgb(0,0,0);">😕</button>
							<button name="rating" value="1" class="btn btn-primary btn-lg"
                type="submit" style="margin-right:0px;height:250px;width:250px;background-color:rgb(195,31,20);box-shadow:none;border-color:white;">☹️</button>
                    </form>
            
                        </div>
						<div class="row">
							<div class="col align-self-center">
								<p class="text-center" style="margin-right:0px;margin-left:730px;font-size:29px;">NOTIFICATION WILL BE SENT</p>
							</div>
						</div>
						<div></div>
						<div class="clearfix"></div>
						<script src="{% static 'js/jquery.min.js' %}"></script>
						<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
					</body>
				</html>


 -->

husky/feedback/templates/feedback/problem.html
{% load staticfiles %}

<!-- Amin Husni - 2018 -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Husky_Feedbacklist</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <style>

            .nopad {
                padding-left: 0 !important;
                padding-right: 0 !important;
            }
            /*image gallery*/
            .image-checkbox {
                cursor: pointer;
                box-sizing: border-box;
                -moz-box-sizing: border-box;
                -webkit-box-sizing: border-box;
                border: 4px solid transparent;
                margin-bottom: 0;
                outline: 0;
            }
            .image-checkbox input[type="checkbox"] {
                display: none;
            }
            
            .image-checkbox-checked {
                border-color: rgb(8, 243, 0);
            }
            .image-checkbox .fa {
              position: absolute;
              color: #4A79A3;
              background-color: #fff;
              padding: 10px;
              top: 0;
              right: 0;
            }
            .image-checkbox-checked .fa {
              display: block !important;
            }
                
    </style>

    

</head>

<body style="background:url( {% static 'img/bg.jpg' %} );background-size:120%;font-family:Verdana;">
    <div class="row">
    <span class="second" style="font-size:30px;margin-top:0;padding:20px;float:left;"><font color="white">Select 1 or more and SUBMIT</font></span>
</div>
    <form action="{% url 'feedback:problem_submit' %}", method="post">
            {% csrf_token %}
            <input type='hidden' name='feedback_id' value='{{ feedback_id }}' /> 
    <div class="row justify-content-center" style="margin-top:0px;">
            <label class="image-checkbox" style="margin-right:100px;margin-bottom:20px">
                <img class="img-responsive" src="{% static 'img/others.png' %}" /><font color="white"><br>&nbsp;&nbsp;&nbsp;Previous User's Fault</font>
                <input type="checkbox" name="fault" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" style="margin-right:100px;margin-bottom:20px">
                
                <img class="img-responsive" src="{% static 'img/choked.png' %}" />
                <figcaption><font color="white" style="display:inline-block; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;Toilet Bowl Clogged</font></figcaption>
            
                <input type="checkbox" name="clogged" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" style="margin-right:100px;margin-bottom:20px" >
                <img class="img-responsive" src="{% static 'img/no-toilet-paper.png' %}" /><figcaption><font color="white" style="display:inline-block; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No Toilet Paper</font></figcaption>
                <input type="checkbox" name="toilet_paper" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" style="margin-right:100px;margin-bottom:20px">
                <img class="img-responsive" src="{% static 'img/faulty-lighting.png' %}" /><figcaption><font color="white" style="display:inline-block; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lighting</font></figcaption>
                <input type="checkbox" name="lighting" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/soap-dispencer-faulty.png' %}" /><figcaption><font color="white" style="display:inline-block; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Soap</font></figcaption>
                <input type="checkbox" name="soap" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
        </div>
        <div class="row justify-content-center" style="margin-top:1px;">
            <label class="image-checkbox" style="margin-right:100px;margin-bottom:20px">
                <img class="img-responsive" src="{% static 'img/flexible-hose-detached.png' %}" /><figcaption><font color="white" style="display:inline-block; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hose</font></figcaption>
                <input type="checkbox" name="hose" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" style="margin-right:100px;margin-bottom:20px">
                <img class="img-responsive" src="{% static 'img/toilet-temperature.png' %}" /><figcaption><font color="white" style="display:inline-block; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Temperature</font></figcaption>
                <input type="checkbox" name="temperature" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" style="margin-right:100px;margin-bottom:20px" >
                <img class="img-responsive" src="{% static 'img/loose.png' %}" /><figcaption><font color="white" style="display:inline-block; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seat Cover</font></figcaption>
                <input type="checkbox" name="bowl" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" style="margin-right:100px;margin-bottom:20px">
                <img class="img-responsive" src="{% static 'img/basin-tap.png' %}" /><figcaption><font color="white" style="display:inline-block; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tap Faulty</font></figcaption>
                <input type="checkbox" name="sink" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/foul-smell.png' %}" /><figcaption><font color="white" style="display:inline-block; text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Foul Smell</font></figcaption>
                <input type="checkbox" name="smell" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
        </div>
        <div class="row justify-content-center" style="margin-top:0px;">
            <button class="btn btn-primary btn-lg" type="submit" value="SUBMIT" style="margin-right:2px;height:89px;width:245px;box-shadow:none;background-color:transparent;border-color:transparent;margin-top:0px;"><img style="margin-right:20px;cursor:pointer;width:200px;"  src="{% static 'img/submit.png' %}" />
            </button>
        </div>
        


    </form>
        
        
        <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

            <script>
                    // image gallery
                    // init the state from the input
                    $(".image-checkbox").each(function () {
                      if ($(this).find('input[type="checkbox"]').first().attr("checked")) {
                        $(this).addClass('image-checkbox-checked');
                      }
                      else {
                        $(this).removeClass('image-checkbox-checked');
                      }
                    });
                    
                    // sync the state to the input
                    $(".image-checkbox").on("click", function (e) {
                      $(this).toggleClass('image-checkbox-checked');
                      var $checkbox = $(this).find('input[type="checkbox"]');
                      $checkbox.prop("checked",!$checkbox.prop("checked"))
                    
                      e.preventDefault();
                    });
                    
                    </script>




        </body>

husky/feedback/templates/feedback/setup.html
<!-- Amin Husni - 2018 -->

<html>
<body>

<h1>This is an initial setup</h1>
<h2>Please set the location of this kiosk</h2>


{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'feedback:setlocation' %}", method="post">
    {% csrf_token %}
    <br>
    Kiosk Location: 
    <br>
    <select name="location_id">
        {% if locations %}
            {% for location in locations %}
                <option value="{{ location.location_id }}">{{ location.location_name }}</option>
            {% endfor %}
        {% endif %}
    </select>
<!--     <br>
    Authorization Code: 
    <br>
    <input name="Auhorization Code" type="text"> -->
    <input type="submit" value="SUBMIT">

  </form>

</body>
</html>

husky/feedback/templates/feedback/thankyou.html
{% load staticfiles %}

<!-- Amin Husni - 2018 -->

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
				<title>Husky</title>
				<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
					<link rel="stylesheet" href="{% static 'css/styles.css' %}">
					</head>
                    <body style="background:url( {% static 'img/bg.jpg' %} );background-size:120%;font-family:Verdana;">
                            
                                    <a href="{% url 'supervisor:index' %}" >
                                            <img class="img-responsive" src="{% static 'img/hidden.png' %}" />
                                    </a>
                                
                                    <font color="white">
                            <div class="row">
                                <div class="col">
                                    <h1 class="text-center" style="height:200px;font-size:100px;margin-top:0px;"><br><strong>We Appreciate Your Feedback</strong></h1>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <p class="text-center" style="font-size:81px;margin-top:173px;">We Will Continue To Improve&nbsp;<br>Our Quality Of Serivce</p>
                                </div>
                            </div>
                            </font>
						<script src="{% static 'js/jquery.min.js' %}"></script>
						<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
					</body>
				</html>


<script type="text/javascript">
    setTimeout(function() {
        window.location.href = "{% url 'feedback:index' %}";
    }, 3000);
</script>