husky/feedback/urls.py
#Amin Husni - 2018
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'feedback'
urlpatterns = [
    path('', views.index, name='index'),
    path('setup.html', views.setup, name='setup'),
    path('setlocation.html', views.setlocation, name='setlocation'),
    path('rating_submit.html', views.rating_submit, name='rating_submit'),
    path('problem.html', views.problem, name='problem'),
    path('problem_submit.html', views.problem_submit, name='problem_submit'),
    path('thankyou.html', views.thankyou, name='thankyou'),

    
]

husky/husky/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponseRedirect

urlpatterns = [
    path('feedback/', include('feedback.urls')),
    path('supervisor/', include('supervisor.urls')),
    path('admin/', admin.site.urls),
]

husky/supervisor/urls.py
#Amin Husni - 2018
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'supervisor'
urlpatterns = [
    path('', views.index, name='index'),
    path('authenticate.html', views.authenticate, name='authenticate'),
    path('checklist.html', views.checklist, name='checklist'),
    path('error.html', views.error, name='error'),
    path('checklist_submit.html', views.checklist_submit, name='checklist_submit'),
    path('supervisor_index.html', views.supervisor_index, name='supervisor_index'),
    path('checklist_report.html', views.checklist_report, name='checklist_report'),
    path('checklist_report_location.html', views.checklist_report_location, name='checklist_report_location'),
    path('performance_report_location.html', views.performance_report_location, name='performance_report_location'),
    path('performance_report.html', views.performance_report, name='performance_report'),
    path('report_csv.html', views.report_csv, name='report_csv'),
]

husky/supervisor/models.py
#Amin Husni - 2018
from django.db import models

class Supervisor(models.Model):

    CLEANER = "CL"
    ADMIN = "AD"
    SUPERVISOR_CHOICES = (
        (CLEANER, 'Cleaner'), 
        (ADMIN, 'Admin'),
    )

    supervisor = models.IntegerField()
    supervisor_type = models.CharField(max_length=2, choices=SUPERVISOR_CHOICES, default=CLEANER,)
    name = models.TextField(max_length=100)
    authorization_token = models.TextField(max_length=100, default=None, blank=True)
    authorization_expire = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        final = str(self.supervisor) + " - " + self.name
        return str(final)


class Checklist(models.Model):

    employee_number = models.ForeignKey(Supervisor, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    location_id = models.TextField(max_length=100)
    
    
    def __str__(self):
        return str(self.created)


class Check_item(models.Model):

    checklist = models.ForeignKey(Checklist, on_delete=models.CASCADE)
    floor = models.BooleanField("Floor", default=False)
    smell = models.BooleanField("Smell", default=False)
    wall = models.BooleanField("Wall", default=False)
    dustbin = models.BooleanField("Dustbin", default=False)
    toilet_bowl = models.BooleanField("Toilet bowl", default=False)
    urinal_bowl = models.BooleanField("Urinal bowl", default=False)
    wash_basin = models.BooleanField("Wash basin", default=False)
    mirror = models.BooleanField("Mirror", default=False)
    tissue = models.BooleanField("Tissue", default=False)
    handsoap = models.BooleanField("Handsoap", default=False)

    def __str__(self):
        date = Checklist.objects.get(created=self.checklist.created)
        date = date.created
        return str(date)

husky/supervisor/views.py
#Amin Husni - 2018
from django.shortcuts import render
from django.shortcuts import redirect
from supervisor.models import Supervisor, Checklist, Check_item
from location.models import Location
from feedback.models import Feedback, Problem
import uuid
from datetime import timedelta
from datetime import datetime
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from django.http import HttpResponse
from django.template import Context, loader

#Decorators
#Authenticate page request if the user has signed in and has it expired. Expiry extended
#if the token has not expired. 
def check_token(func):
    def gunc(*args, **kwargs):

        token_expiry_time = 2

        try:
                token = args[0].COOKIES.get('authorization_token')
                supervisorquery = Supervisor.objects.get(authorization_token=token)
                
        except Exception as e:
                context = {
                        'error': "Token is invalid. Your ID was probably being used somewhere else. Any submission was not recorded",
                }
                return render(args[0], 'supervisor/error.html', context)

        if(supervisorquery.authorization_expire > timezone.now()):
                supervisorquery.authorization_expire = timezone.now() + timedelta(minutes=token_expiry_time)
                supervisorquery.save()
                return func(*args, **kwargs)
        else:
                context = {
                        'error': "Your session has expired. Any submission was not recorded",
                }
                return render(args[0], 'supervisor/error.html', context)      

    return gunc


# Create your views here.
def index(request):
    
        return render(request, 'supervisor/index.html', None)

def authenticate(request):

        token_expiry_time = 2

        try:
                supervisor = Supervisor.objects.get(supervisor=request.POST['supervisor'])
                supervisor.authorization_token = uuid.uuid4().hex
                supervisor.authorization_expire = timezone.now() + timedelta(minutes=token_expiry_time)
                supervisor.save()
                response = redirect('supervisor:supervisor_index')
                response.set_cookie('authorization_token', supervisor.authorization_token)
                return response

        except:
                return redirect('feedback:index')

@check_token
def checklist(request):
        
        return render(request, 'supervisor/checklist.html', None)

@check_token
def supervisor_index(request):

        if not request.COOKIES.get('location_id'):
                locationsetting = False
        else:
                locationsetting = True
        
        context = {
                        'locationsetting': locationsetting,
                }

        return render(request, 'supervisor/supervisor_index.html', context)

@check_token
def checklist_submit(request):

        try:
                token = request.COOKIES.get('authorization_token')
                supervisorquery = Supervisor.objects.get(authorization_token=token)
                
        except Exception as e:
                context = {
                        'error': "Token is invalid. Your ID was probably being used somewhere else. Any submission was not recorded",
                }
                return render(request, 'supervisor/error.html', context)

        pcheck = Checklist(location_id=request.COOKIES.get('location_id'), employee_number=supervisorquery)
        pcheck.save()

        if 'checklist' not in request.POST:
                checklist = False
        else:
                checklist = bool(request.POST['checklist'])   

        if 'floor' not in request.POST:
                floor = False
        else:
                floor = bool(request.POST['floor'])

        if 'smell' not in request.POST:
                smell = False
        else:
                smell = bool(request.POST['smell'])

        if 'wall' not in request.POST:
                wall = False
        else:
                wall = bool(request.POST['wall'])

        if 'dustbin' not in request.POST:
                dustbin = False
        else:
                dustbin = bool(request.POST['dustbin'])

        if 'toilet_bowl' not in request.POST:
                toilet_bowl = False
        else:
                toilet_bowl = bool(request.POST['toilet_bowl'])

        if 'urinal_bowl' not in request.POST:
                urinal_bowl = False
        else:
                urinal_bowl = bool(request.POST['urinal_bowl'])

        if 'wash_basin' not in request.POST:
                wash_basin = False
        else:
                wash_basin = bool(request.POST['wash_basin'])

        if 'mirror' not in request.POST:
                mirror = False
        else:
                mirror = bool(request.POST['mirror'])

        if 'tissue' not in request.POST:
                tissue = False
        else:
                tissue = bool(request.POST['tissue'])

        if 'handsoap' not in request.POST:
                handsoap = False
        else:
                handsoap = bool(request.POST['handsoap'])

        checklist = Check_item(checklist=pcheck, floor=floor, smell=smell, wall=wall, dustbin=dustbin, toilet_bowl=toilet_bowl, urinal_bowl=urinal_bowl, wash_basin=wash_basin, mirror=mirror, tissue=tissue, handsoap=handsoap)
        checklist.save()

        return redirect('feedback:thankyou')



def error(request):
        pass

@check_token
def checklist_report(request):
        #This is the monthly report generator. 

        location_id = request.POST['location_id']
        print(location_id)

        lokasi = Location.objects.filter(location_id=location_id).first()
        location_name = lokasi.location_name
        #Calculate for last month
        target_month = datetime.now() - relativedelta(months=0)
        month_str = target_month.strftime("%B")

        report = Checklist.objects.filter(created__month=target_month.month, location_id=location_id).prefetch_related('check_item_set')
        fieldnames = Check_item._meta.get_fields()

        #Skip first two elements
        iternames = iter(fieldnames)
        next(iternames)
        next(iternames)

        context = {
                'month': month_str,
                'report': report,
                'iternames': iternames,
                'location_name': location_name,
                'location_id': location_id,
        }

        return render(request, 'supervisor/checklist_report.html', context)

@check_token
def report_csv(request):
        
        #This is the monthly report generator. 

        response = HttpResponse(content_type='text/html')
        response['Content-Disposition'] = 'attachment; filename="monthlyreport.csv"'

        location_id = request.POST['location_id']
        print(location_id)

        lokasi = Location.objects.filter(location_id=location_id).first()
        location_name = lokasi.location_name
        #Calculate for last month
        target_month = datetime.now() - relativedelta(months=0)
        month_str = target_month.strftime("%B")

        report = Checklist.objects.filter(created__month=target_month.month, location_id=location_id).prefetch_related('check_item_set')
        fieldnames = Check_item._meta.get_fields()

        #Skip first two elements
        iternames = iter(fieldnames)
        next(iternames)
        next(iternames)

        list_of_col = []

        for fieldname in iternames:
                list_of_col.append(fieldname.verbose_name)

        render_list_of_col = ','.join(list_of_col)

        context = {
                'month': month_str,
                'report': report,
                'iternames': render_list_of_col,
                'location_name': location_name,
                'location_id': location_id,
        }

        t = loader.get_template('supervisor/monthly_report.txt')
        response.write(t.render(context))

        return response

@check_token
def checklist_report_location(request):
        locations = Location.objects.all()
        location_name = ""
        location_id = ""


        if not request.COOKIES.get('location_id'):
                locationsetting = False
        else:
                locationsetting = True
                location_id = request.COOKIES.get('location_id')
                print(location_id)
                lokasi = Location.objects.filter(location_id=location_id).first()
                location_name = lokasi.location_name
        


        context = {
        'locations': locations,
        'location_name': location_name,
        'location_id': location_id,
        'locationsetting': locationsetting,
        }
        return render(request, 'supervisor/checklist_report_location.html', context)

@check_token
def performance_report_location(request):
        locations = Location.objects.all()
        location_name = ""
        location_id = ""

        if not request.COOKIES.get('location_id'):
                locationsetting = False
        else:
                locationsetting = True
                location_id = request.COOKIES.get('location_id')
                print(location_id)
                lokasi = Location.objects.filter(location_id=location_id).first()
                location_name = lokasi.location_name

        context = {
        'locations': locations,
        'location_name': location_name,
        'location_id': location_id,
        'locationsetting': locationsetting,
        }
        return render(request, 'supervisor/performance_report_location.html', context)

@check_token
def performance_report(request):
        location_id = request.POST['location_id']

        lokasi = Location.objects.filter(location_id=location_id).first()
        location_name = lokasi.location_name


        #Calculate for today
        target_day = datetime.now() - relativedelta(days=0)
        day_str = target_day.strftime("%A %d %b %Y")

husky/supervisor/templates/supervisor/checklist.html
<!-- Amin Husni - 2018 -->




{% load staticfiles %}

<!-- Amin Husni - 2018 -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Husky_Feedbacklist</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <style>

            .nopad {
                padding-left: 0 !important;
                padding-right: 0 !important;
            }
            /*image gallery*/
            .image-checkbox {
                cursor: pointer;
                box-sizing: border-box;
                -moz-box-sizing: border-box;
                -webkit-box-sizing: border-box;
                border: 4px solid transparent;
                margin-bottom: 0;
                outline: 0;
            }
            .image-checkbox input[type="checkbox"] {
                display: none;
            }
            
            .image-checkbox-checked {
                border-color: rgb(8, 243, 0);
            }
            .image-checkbox .fa {
              position: absolute;
              color: #4A79A3;
              background-color: #fff;
              padding: 10px;
              top: 0;
              right: 0;
            }
            .image-checkbox-checked .fa {
              display: block !important;
            }
                
    </style>

    

</head>

<body style="overflow:hidden;">
    <h1 class="text-center" style="height:256px;font-size:100px;padding:69px;">Supervisor Checklist</h1>
    
    <form action="{% url 'supervisor:checklist_submit' %}", method="post">
            {% csrf_token %}
            <input type='hidden' name='supervisor_id' value='{{ supervisor_id }}' />  
    <div class="row justify-content-center" style="margin-top:100px;">
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/floor.jpg' %}" />
                <input type="checkbox" name="floor" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/smell.jpg' %}" />
                <input type="checkbox" name="smell" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/wall.jpg' %}" />
                <input type="checkbox" name="wall" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/dustbin.jpg' %}" />
                <input type="checkbox" name="dustbin" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/bowl.jpg' %}" />
                <input type="checkbox" name="toilet_bowl" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
        </div>
        <div class="row justify-content-center" style="margin-top:1px;">
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/urinal.jpg' %}" />
                <input type="checkbox" name="urinal_bowl" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/sink.gif' %}" />
                <input type="checkbox" name="wash_basin" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/mirror.jpg' %}" />
                <input type="checkbox" name="mirror" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/toilet_paper.jpg' %}" />
                <input type="checkbox" name="tissue" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
            <label class="image-checkbox" >
                <img class="img-responsive" src="{% static 'img/soap.jpg' %}" />
                <input type="checkbox" name="handsoap" value="True" style="margin-right:2px;height:250px;width:250px; "/>
                <i class="fa fa-check hidden"></i>
            </label>
        </div>
        <div class="row justify-content-center" style="margin-top:1px;">
            <button class="btn btn-primary btn-lg" type="submit" value="SUBMIT" style="margin-right:2px;height:89px;width:245px;box-shadow:none;background-color:rgb(43,201,79);border-color:white;margin-top:30px;">SUBMIT</button>
        </div>
        


    </form>
        
        
        <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

            <script>
                    // image gallery
                    // init the state from the input
                    $(".image-checkbox").each(function () {
                      if ($(this).find('input[type="checkbox"]').first().attr("checked")) {
                        $(this).addClass('image-checkbox-checked');
                      }
                      else {
                        $(this).removeClass('image-checkbox-checked');
                      }
                    });
                    
                    // sync the state to the input
                    $(".image-checkbox").on("click", function (e) {
                      $(this).toggleClass('image-checkbox-checked');
                      var $checkbox = $(this).find('input[type="checkbox"]');
                      $checkbox.prop("checked",!$checkbox.prop("checked"))
                    
                      e.preventDefault();
                    });
                    
                    </script>




        </body>

husky/supervisor/templates/supervisor/checklist_report.html
<!-- Amin Husni - 2018 -->
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
<style>
table, th, td {
    border: 1px solid black;
}
</style>
</head>
<body>

<h1>MONTHLY REPORT - CHECKLIST </h1>
<h2>For the month of {{ month }} </h2>
<h3>Location: {{ location_name }}<br> Location ID: {{ location_id }}</h3>

<table>


  <tr>
    
    <th>Date</th>
    {% for fieldname in iternames %}
    <th>{{ fieldname.verbose_name }}</th>
    {% endfor %}
    <th>Supervisor</th>
  </tr>



    {% for checklist in report %}
    <tr>
        <th>{{ checklist.created }}</th>
        <th>{{ checklist.check_item_set.all.first.floor }}</th>
        <th>{{ checklist.check_item_set.all.first.smell }}</th>
        <th>{{ checklist.check_item_set.all.first.wall }}</th>
        <th>{{ checklist.check_item_set.all.first.dustbin }}</th>
        <th>{{ checklist.check_item_set.all.first.toilet_bowl }}</th>
        <th>{{ checklist.check_item_set.all.first.urinal_bowl }}</th>
        <th>{{ checklist.check_item_set.all.first.wash_basin }}</th>
        <th>{{ checklist.check_item_set.all.first.mirror }}</th>
        <th>{{ checklist.check_item_set.all.first.tissue }}</th>
        <th>{{ checklist.check_item_set.all.first.handsoap }}</th>
        <th>{{ checklist.employee_number.supervisor}} - {{checklist.employee_number.name}}</th>

        
    </tr>
    {% endfor %}



</table>
<form action="{% url 'supervisor:authenticate' %}", method="post">
        {% csrf_token %}
<div class="row " style="margin-top:0px;">
        <button class="btn btn-primary btn-lg" value="cancel" type="submit" formaction="{% url 'supervisor:checklist_report_location' %}"style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(220, 0, 0);border-color:white;margin-top:20px;">BACK</button>
    </div>
</form>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

husky/supervisor/templates/supervisor/checklist_report_location.html
<!-- Amin Husni - 2018 -->




{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Husky</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body style="overflow:hidden;">
    <div class="row">
        <div class="col">
            <h1 class="text-center" style="height:256px;font-size:100px;padding:140px;">MONTHLY REPORT</h1>
            {% if locationsetting == True %}
        <h1 class="text-center" >You are currently accessing this console from {{ pass }}</h1>
        <h3 class="text-center" >Location: {{ location_name }}<br> Location ID: {{ location_id }}</h3>
        {% endif %}
        </div>
    </div>

    <form action="{% url 'supervisor:checklist_report' %}", method="post">
            {% csrf_token %}
    <div class="row justify-content-center align-items-center" style="margin-top:100px;">
        <div class="col"></div>
        <div class="col align-self-center">
                <div class="centerBlock">
                <select name="location_id">
                        {% if locations %}
                            {% for location in locations %}
                                <option  value="{{ location.location_id }}">{{ location.location_name }}</option>
                            {% endfor %}
                        {% endif %}
                    </select>
                </div>
        </div>
        <div class="col"></div>
    </div>
    <div class="row justify-content-center" style="margin-top:-40px;">
        <button class="btn btn-primary btn-lg" type="submit" value="Preview Report" style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(43,201,79);border-color:white;margin-top:100px;">PREVIEW REPORT</button>
        <button class="btn btn-primary btn-lg" type="submit" value="Generate CSV Report" formaction="{% url 'supervisor:report_csv' %}" style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(43,201,79);border-color:white;margin-top:100px;">GENERATE CSV REPORT</button>
    </div>

        <div class="row justify-content-center" style="margin-top:0px;">
                <button class="btn btn-primary btn-lg" value="cancel" type="submit" formaction="{% url 'feedback:index' %}"style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(220, 0, 0);border-color:white;margin-top:20px;">CANCEL</button>
            </div>

</form>

    <div class="clearfix"></div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>



    <style>
    .centerBlock {
        display: table;
        margin: auto;
      }
            </style>

</body>

</html>

husky/supervisor/templates/supervisor/error.html
<!-- Amin Husni - 2018 -->

<h1>Something went wrong! </h1>

{% if error %}
    <p><strong>{{ error }}</strong></p>
{% endif %}

<script type="text/javascript">
    setTimeout(function() {
        window.location.href = "{% url 'feedback:index' %}";
    }, 2000);
</script>

husky/supervisor/templates/supervisor/index.html
<!-- Amin Husni - 2018 -->

{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Husky</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body style="overflow:hidden;">
    <div class="row">
        <div class="col">
            <h1 class="text-center" style="height:256px;font-size:100px;padding:140px;">Supervisor Section</h1>
        </div>
    </div>
    <form action="{% url 'supervisor:authenticate' %}", method="post">
            {% csrf_token %}
    <div class="row justify-content-center" style="margin-top:80px;">
        <div class="col"></div>
        <div class="col"><input class="form-control-lg" type="password" name="supervisor" placeholder="ENTER SUPERVISOR PIN" style="width:590px;"></div>
        <div class="col"></div>
    </div>
    <div class="row justify-content-center" style="margin-top:0px;">
        <button class="btn btn-primary btn-lg" value="SUBMIT" type="submit" style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(43,201,79);border-color:white;margin-top:50px;">LOGIN</button>
    </div>
    <div class="row justify-content-center" style="margin-top:0px;">
        <button class="btn btn-primary btn-lg" value="cancel" type="submit" formaction="{% url 'feedback:index' %}"style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(220, 0, 0);border-color:white;margin-top:20px;">CANCEL</button>
    </div>


</form>
    <div class="clearfix"></div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>


<script type="text/javascript">
    setTimeout(function() {
        window.location.href = "{% url 'feedback:index' %}";
    }, 20000);
</script>

husky/supervisor/templates/supervisor/supervisor_index.html
{% load staticfiles %}

<!-- Amin Husni - 2018 -->


<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Husky</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body style="overflow:hidden;">
    <div class="row">
        <div class="col">
            <h1 class="text-center" style="height:256px;font-size:100px;padding:140px;">What Would You Like To Do Today?</h1>
        </div>
    </div>
    {% if locationsetting == True %}
    <div class="row justify-content-center" style="margin-top:100px;">
            <form action="{% url 'supervisor:checklist' %}">
        <button class="btn btn-primary btn-lg" type="submit" style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(43,201,79);border-color:white;margin-top:51px;">SUBMIT CHECKLIST</button>
    </form>
    </div>
    {% endif %}
    
        <div class="row justify-content-center" style="margin-top:-40px;">
                <form action="{% url 'supervisor:checklist_report_location' %}">
        <button class="btn btn-primary btn-lg" type="submit" style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(43,201,79);border-color:white;margin-top:51px;">MONTHLY REPORT</button>
    </form>
    </div>
    
        <div class="row justify-content-center" style="margin-top:-40px;">
                <form action="{% url 'supervisor:performance_report_location' %}">
            <button class="btn btn-primary btn-lg" type="submit" style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(43,201,79);border-color:white;margin-top:51px;">DAILY PERFORMANCE STATUS</button>
        </form>
        </div>
        <div class="row justify-content-center" style="margin-top:-40px;">
                <form action="{% url 'feedback:index' %}">
            <button class="btn btn-primary btn-lg" type="submit" style="margin-right:2px;height:76px;width:613px;box-shadow:none;background-color:rgb(211, 47, 47);border-color:white;margin-top:51px;">EXIT</button>
        </form>
        </div>
        
    <div class="clearfix"></div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>